// <auto-generated />
namespace SocialNetwork.Migrations.PhotoCommentContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdatePhotoLogicAddCommentsFKConstraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatePhotoLogicAddCommentsFKConstraint));
        
        string IMigrationMetadata.Id
        {
            get { return "201909261234272_Update-Photo-Logic-AddCommentsFKConstraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
