// <auto-generated />
namespace SocialNetwork.Migrations.PhotoCommentContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class photoFilePathNotAbsolutePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(photoFilePathNotAbsolutePath));
        
        string IMigrationMetadata.Id
        {
            get { return "201909221925160_photoFilePath-Not-AbsolutePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
