// <auto-generated />
namespace SocialNetwork.Migrations.PhotoCommentContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RepopulatePhotosComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RepopulatePhotosComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201909222014135_Repopulate-Photos-Comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
